export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

export const GET_SINGLE_PROJECTS_REQUEST = "GET_SINGLE_PROJECTS_REQUEST";
export const GET_SINGLE_PROJECTS_SUCCESS = "GET_SINGLE_PROJECTS_SUCCESS";
export const GET_SINGLE_PROJECTS_FAILURE = "GET_SINGLE_PROJECTS_FAILURE";

export const CREATE_PROJECTS_REQUEST = "CREATE_PROJECTS_REQUEST";
export const CREATE_PROJECTS_SUCCESS = "CREATE_PROJECTS_SUCCESS";
export const CREATE_PROJECTS_FAILURE = "CREATE_PROJECTS_FAILURE";


export const UPDATE_PROJECTS_REQUEST = "UPDATE_PROJECTS_REQUEST";
export const UPDATE_PROJECTS_SUCCESS = "UPDATE_PROJECTS_SUCCESS";
export const UPDATE_PROJECTS_FAILURE = "UPDATE_PROJECTS_FAILURE";

export const DELETE_PROJECTS_REQUEST = "DELETE_PROJECTS_REQUEST";
export const DELETE_PROJECTS_SUCCESS = "DELETE_PROJECTS_SUCCESS";
export const DELETE_PROJECTS_FAILURE = "DELETE_PROJECTS_FAILURE"