export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";


export const CREATE_USER_REQUEST = "CREATE_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_SUCCESS";
export const DELETE_uSER_FAILURE = "DELETE_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_FAILURE";